# Generated by Django 3.1.3 on 2020-12-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='ip',
            field=models.CharField(default=1, max_length=15, verbose_name='IP адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='star',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.ratingstar', verbose_name='звезда'),
            preserve_default=False,
        ),
    ]
